apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-app
  template:
    metadata:
      labels:
        app: notifications-app
    spec:
      containers:
        - name: notifications-container
          image: week10-app-s12:latest
          ports:
            - containerPort: 8211
          livenessProbe:
            httpGet:
              path: /health
              port: 8211
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8211
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
