# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x10notifications.v1\"(\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"\'\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x10SubscribeRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"3\n\x06Update\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t2\xa4\x01\n\x14NotificationsService\x12?\n\x06\x43reate\x12\x19.notifications.v1.Request\x1a\x1a.notifications.v1.Response\x12K\n\tSubscribe\x12\".notifications.v1.SubscribeRequest\x1a\x18.notifications.v1.Update0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=35
  _globals['_REQUEST']._serialized_end=75
  _globals['_RESPONSE']._serialized_start=77
  _globals['_RESPONSE']._serialized_end=116
  _globals['_SUBSCRIBEREQUEST']._serialized_start=118
  _globals['_SUBSCRIBEREQUEST']._serialized_end=168
  _globals['_UPDATE']._serialized_start=170
  _globals['_UPDATE']._serialized_end=221
  _globals['_NOTIFICATIONSSERVICE']._serialized_start=224
  _globals['_NOTIFICATIONSSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
