replicaCount: 2
containerName: orders-container
image:
  repository: orders-s12
  tag: "stage"
service:
  name: orders-svc-s12
  port: 8282
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
