# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07logs.v1\".\n\x10\x43reateLogRequest\x12\x0b\n\x03log\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\"$\n\x11\x43reateLogResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\x0bLogsService\x12\x42\n\tCreateLog\x12\x19.logs.v1.CreateLogRequest\x1a\x1a.logs.v1.CreateLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATELOGREQUEST']._serialized_start=26
  _globals['_CREATELOGREQUEST']._serialized_end=72
  _globals['_CREATELOGRESPONSE']._serialized_start=74
  _globals['_CREATELOGRESPONSE']._serialized_end=110
  _globals['_LOGSSERVICE']._serialized_start=112
  _globals['_LOGSSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
